# Generated by Django 2.2.5 on 2019-09-07 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('yearRange', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=500)),
                ('studentType', models.CharField(max_length=500)),
                ('tuitionFee', models.FloatField()),
            ],
            options={
                'verbose_name': 'Ranking',
                'db_table': 'Ranking',
            },
        ),
    ]
